### ISSUE TITLE
biosamples are not connected directly to projects in JSON

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-metadata#101]
our schema has:

```yaml
  omics processing:
    is_a: biosample processing
    description: >-
      The methods and processes used to generate omics data from a biosample or organism.
    slots:
      - part of
      - has output
    slot_usage:
      id:
        description: >-
          The primary identifier for the omics processing. E.g. GOLD:GpNNNN
      name:
        description: >-
          A human readable name or description of the omics processing.
      alternate identifiers:
        description: >-
          The same omics processing may have distinct identifiers in different databases (e.g. GOLD and EMSL)
      part of:
        range: study
      has output:
        range: data object
```

so an omics_processing object is linked to a study, but not a sample

Example instance data:

```yaml
  omics_processing_set: 
    - 
      id: "gold:Gp0108335"
      name: "Thawing permafrost microbial communities from the Arctic, studying carbon transformations - Permafrost 712P3D"
      part_of: 
        - "gold:Gs0112340"
      has_output: 
        - "nmdc:5af44fd364d0b33747747ddb"
        - "nmdc:5af44fd264d0b33747747dd9"
        - "jgi:551a20d30d878525404e90d5"
      type: "nmdc:OmicsProcessing"
      add_date: 
        has_raw_value: "30-OCT-14 12.00.00.000000000 AM"
      mod_date: 
        has_raw_value: "22-MAY-20 06.13.12.927000000 PM"
      ncbi_project_name: 
        has_raw_value: "Thawing permafrost microbial communities from the Arctic, studying carbon transformations - Permafrost 712P3D"
      omics_type: 
        has_raw_value: "Metagenome"
      principal_investigator_name: 
        has_raw_value: "Virginia Rich"
```

which corresponds to https://gold.jgi.doe.gov/project?id=Gp0108335 -- note this has a link 
https://gold.jgi.doe.gov/project?id=Gp0108335
