### ISSUE TITLE
is-a link broken for gold path slots

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-metadata#146]
The is-a link is broken for GOLD path fields; e.g.: https://microbiomedata.github.io/nmdc-metadata/docs/ecosystem.html.

@deepakunni3 could this be a problem with how the documentation is generated? Could the lack of a blank line after "TODO" cause this?

Here is an example of they yaml:
```
gold_path_field:
    is_a: attribute
    range: attribute value
    abstract: true
    description: >-
      This is a grouping for any of the gold path fields
    
  ecosystem:
    is_a: gold_path_field
    description: >-
      TODO
ecosystem:
    is_a: gold_path_field
    description: >-
      TODO
  ecosystem_category:
    is_a: gold_path_field
    description: >-
      TODO
  ecosystem_type:
    is_a: gold_path_field
    description: >-
      TODO
  ecosystem_subtype:
    is_a: gold_path_field
    description: >-
      TODO
  specific_ecosystem:
    is_a: gold_path_field
    description: >-
      TODO
```

cc @cmungall
