### ISSUE TITLE
Define ontology for soil treatments

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-metadata#166]
For experimental factor we have:

```yaml
  experimental_factor:
    aliases:
      - experimental factor
    description: >-
       "Experimental factors are essentially the variable aspects of an experiment design which can be used to describe an experiment, or set of experiments, in an increasingly detailed manner. This field accepts ontology terms from Experimental Factor Ontology (EFO) and/or Ontology for Biomedical Investigations (OBI). For a browser of EFO (v 2.95) terms, please see http://purl.bioontology.org/ontology/EFO; for a browser of OBI (v 2018-02-12) terms please see http://purl.bioontology.org/ontology/OBI"
    multivalued: false
    is_a: attribute
    range: controlled term value  ## syntax: {termLabel} {[termID]}|{text}
    mappings:
      - MIxS:experimental_factor
    in_subset:
      - investigation
```

This is very biomedical focused guidelines

We need some recommendations for non-biomedical scenarios

e.g.

 - http://obofoundry.org/ontology/peco Plant Experimental Conditions Ontology

cc @mslarae13
