### ISSUE TITLE
document mapping between NMDC-style GFF3 and schema annotation component

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-metadata#184]
The schema has inline docs detailing the mapping but we should provide a higher level guide. I will sketch out in this ticket and then this can be turned into docs on the site. I'm doing quickly so if anything is confusing, it's likely I made a mistake. I will also give examples in yaml but the json cognate should be obvious

Example

```
Ga0185794_41    GeneMark.hmm-2 v1.05    CDS     48      1037    56.13   +       0       ID=Ga0185794_41_48_1037;translation_table=11;start_type=ATG;product=5-methylthioadenosine/S-adenosylhomocysteine deaminase;product_source=KO:K12960;cath_funfam=3.20.20.140;cog=COG0402;ko=KO:K12960;ec_number=EC:3.5.4.28,EC:3.5.4.31;pfam=PF01979;superfamily=51338,51556
```

This GFF line represents the output of structural annotation (the prediction of a CDS on sequence Ga0185794_41). This is given a protein ID (skolemized from reference + coordinates). `Ga0185794_41_48_1037`. Col9 represents the outputs of functional annotation. @scanon @hubin-keio do I have this right?

The core feature would be represented as an instance of
https://microbiomedata.github.io/nmdc-metadata/docs/GenomeFeature

![image](https://user-images.githubusercontent.com/50745/102566326-29780100-4094-11eb-8e12-120b99bae3c3.png)

so our initial object would look like:

```yaml
seqid: NMDC:Ga0185794_41 
start: 48
end: 1037
strand: "+"
type: SO:0000316 ## note we use a key to the SO object which is itself an instance of ControlledTerm
encodes: NMDC:Ga0185794_41_48_1037
```

Note all IDs are prefixed to conform to the NMDC identifiers standards doc

Note the 'encodes' field, to link to a GeneProduct (this will always be a Protein for the current pipeline, but in future we may have ncRNA annotations)

https://microbiomedata.github.io/nmdc-metadata/docs/GeneProduct

Currently the GeneProduct field is fairly bare, but in future additional fields could be added - e.g. AA seq. The GeneProduct is what functional annotations are attached to

https://microbiomedata.github.io/nmdc-metadata/docs/FunctionalAnnotation

Each ';` separated section in col9 of the GFF would correspond to a separate annotation. The annotation links the gene product to the [controlled term](https://microbiomedata.github.io/nmdc-metadata/docs/FunctionalAnnotationTerm)

Minimally this looks like:

```yaml
subject: NMDC:Ga0185794_41_48_1037.  ## this is the protein ID
has_function: KO:K12960
was_informed_by: <...provenance here>
```

For people familiar with the GO annotation system, each entry here represents a line in GAF or GPAD format files.

There would be one entry for each annotation. Above I am only showing the KO annotation

Note the string KO:K12960 is a key to a [controlled term](https://microbiomedata.github.io/nmdc-metadata/docs/FunctionalAnnotationTerm) object. An example would be:

```yaml
id: KEGG.KO:K12960.  ## note we follow identifiers.org standards here for unique IDs
name: mtaD
description: 5-methylthioadenosine/S-adenosylhomocysteine deaminase
```

This is a minimal representation of the KEGG KO object. It can be linked to other controlled term objects. For example, it can include mappings to other systems (EC), parent/child hierarchies, links to pathways, etc, and these can all be traced to compounds chemical entities. However, we will only support simple KO search for GSP, so I will not detail that here. Please refer to #176 for using pathway knowledge to implement more advanced search.

Annotations to other systems (e.g. Pfam) are handled analogously. Please see the `id_prefixes` field in the schema to see the canonical ID prefix for each system.
