### ISSUE TITLE
subsurface_depth

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-metadata#277]
Isee this in the latest gold conversion

```
      id: "gold:Gb0119259"
      name: "Deep subsurface shale carbon reservoir microbial communities from Ohio, USA - Utica-2 Time Series 2014_10_10"
      lat_lon: 
        has_raw_value: "40.178000000000004 -81.07300000000001"
        latitude: 40.178000000000004
        longitude: -81.07300000000001
        type: "nmdc:GeolocationValue"
      env_broad_scale: 
        has_raw_value: "ENVO:00000446"
        term: 
          id: "ENVO:00000446"
      env_local_scale: 
        has_raw_value: "ENVO:01000941"
        term: 
          id: "ENVO:01000941"
      env_medium: 
        has_raw_value: "ENVO:02000119"
        term: 
          id: "ENVO:02000119"
      geo_loc_name: 
        has_raw_value: "USA: Ohio"
      collection_date: 
        has_raw_value: "2014-10-10"
      ecosystem: 
        has_raw_value: "Environmental"
      ecosystem_category: 
        has_raw_value: "Terrestrial"
      ecosystem_type: 
        has_raw_value: "Deep subsurface"
      ecosystem_subtype: 
        has_raw_value: "Unclassified"
      specific_ecosystem: 
        has_raw_value: "Unclassified"
      type: "nmdc:Biosample"
      add_date: 
        has_raw_value: "15-AUG-15 12.00.00.000000000 AM"
      community: 
        has_raw_value: "microbial communities"
      habitat: 
        has_raw_value: "Deep subsurface"
      identifier: 
        has_raw_value: "Utica-2 Time Series 2014_10_10"
      location: 
        has_raw_value: "Ohio"
      mod_date: 
        has_raw_value: "08-JAN-20 02.49.25.000000000 PM"
      ncbi_taxonomy_name: 
        has_raw_value: "subsurface metagenome"
      sample_collection_site: 
        has_raw_value: "Aqueous Sample"
      subsurface_depth: 
        has_raw_value: "2000.0"
```

multiple issues here

 - does not conform to syntax. what is unit?
 - surely we should use samp_tvdss in mixs?
 - subsurface_depth is declared as a slot, but is not an allowable slot in biosample, so why doesn't this fail json schem avalidation?
