### ISSUE TITLE
N50 and L50 definitions are inverted

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-metadata#304]
all the definitions for slots `{ctg,scaf}_[N|L]\d+` need checked. It looks like N50 and L50 need inverted, as does N90 and L90, etc

**Comment by chienchi** [comment]
I think that definition is from BBtools stats.  Brian believes the proper notation should be N50=number of contigs making 50% of the assembly and L50=length lower limit of contigs making up 50% of the assembly.

**Comment by chienchi** [comment]
@scanon @hubin-keio Do you have any comment?  We use bbtools to get the assembly stats. However, bbtools defines the N50 and L50 is opposite to what [Wikipedia](https://en.wikipedia.org/wiki/N50,_L50,_and_related_statistics) says.

**Comment by cmungall** [comment]
just for reference this is what we have now. The body of the text for N50 references L50, and the body of the text for L50 references N50, so it looks like whatever the canonical answer we have an inversion on our part:

```
  scaf_N50:
    is_a: metagenome assembly parameter
    description: >-
      Given a set of scaffolds, each with its own length, the L50 count is defined as the smallest number of scaffolds whose length sum makes up half of genome size.
    range: float

  scaf_L50:
    is_a: metagenome assembly parameter
    description: >-
      Given a set of scaffolds, the N50 is defined as the sequence length of the shortest scaffold at 50% of the total genome length.
    range: float
```
