### ISSUE TITLE
Add more integrity checks on fields in JSON schema 2

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-metadata#360]
There are different levels of checks, this issue is to cover the first 2:

1. Is the ID prefix valid? (e.g. KEGG.KO vs KEGG.ORTHOLOG)
2 Is the local part of the ID syntactically conformant? (e.g. KEGG:K\d+)

The first is very easy to do with using the existing id_prefixes annotated in the schema

**Comment by ssarrafan** [comment]
Continuation of work discussed (at least on GH) from the May sprint at https://github.com/microbiomedata/nmdc-metadata/issues/308

**Comment by ssarrafan** [comment]
Third level of checks handled in https://github.com/microbiomedata/nmdc-metadata/issues/362

**Comment by ssarrafan** [comment]
Removing other assignees. @turbomam let me know if this assignment isn't you.

**Comment by turbomam** [comment]
RE _Is the ID prefix valid? (e.g. KEGG.KO vs KEGG.ORTHOLOG)_

I see prefix definitions, especially in `nmdc-schema/src/schema/annotation.yaml`

```bash
MAM@MAM-M74 schema % pwd
/Users/MAM/Documents/gitrepos/nmdc-schema/src/schema
MAM@MAM-M74 schema % grep -i kegg *
annotation.yaml:      - KEGG.PATHWAY
annotation.yaml:      - KEGG.REACTION
annotation.yaml:      - KEGG.ORTHOLOGY  ## KO number
core.yaml:      - KEGG.COMPOUND
```

Anywhere else I should be looking? @wdduncan @cmungall

**Comment by turbomam** [comment]
RE _Is the local part of the ID syntactically conformant? (e.g. KEGG:K\d+)_

I don't see patterns for the local parts, at least not in `nmdc-schema/src/schema/annotation.yaml`


```yaml
  pathway:
    aliases:
      - biological process
      - metabolic pathway
      - signaling pathway
    is_a: functional annotation term
    description: >-
      A pathway is a sequence of steps/reactions carried out by an organism or community of organisms
    slot_usage:
      has_part:
        range: reaction
        multivalued: true
        description: >-
          A pathway can be broken down to a series of reaction step
    id_prefixes:
      - KEGG.PATHWAY
      - COG
    exact_mappings:
      - biolink:Pathway
```

**Comment by turbomam** [comment]
FInally, I must have forgotten where to find the data that need to be validated against these prefixes and local patterns

@ssarrafan

**Comment by turbomam** [comment]
write generic python code. no test data at this point.

**Comment by turbomam** [comment]
very rough example for  `nmdc-schema/src/schema/annotation.yaml` from @cmungall 

```yaml
functional annotation term:
    aliases:
      - function
      - functional annotation
    is_a: ontology class
    slot_usage:
      id:
        pattern: "^(KEGG.ORTHOLOG:K\\d+|EC:\\d+\\.ETC)$"
    description: >-
      Abstract grouping class for any term/descriptor that can be applied to a functional unit of a genome (protein, ncRNA, complex).
    abstract: true
    todos:
      - decide if this should be used for product naming
```
