### ISSUE TITLE
S4G2 - Metadata ingest, extract metadata from spreadsheets

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-metadata#375]
Extraction of metadata from the spreadsheets when completed (Bill/Mark/Chris)
- Develop a script to extract the metadata from the spreadsheet
- Transform the metadata into JSON
- Develop a script to validate the extracted metadata against the schema

**Comment by cmungall** [comment]
I think this may be simpler

 - The task is to map from the spreadsheet to NMDC schema compliant JSON
 - We already have validators for this

**Comment by turbomam** [comment]
@cmungall If I understand you correctly, that's exacting what I'm working towards. At least the conversion part. Not the validation part yet. That's what motivated my questions about determining the classes in a linkml model, including all imports.

**Comment by turbomam** [comment]
See https://github.com/microbiomedata/nmdc-metadata/blob/issue-375/notebooks/nmdc_metadata_issue_375_prototype.ipynb

**Comment by turbomam** [comment]
Disregarding issues X Y and Z, the study data from the example NMDC Sample Metadata Template looks like this:

```YAML
{'doi': {'has raw value': 'https://doi.org/10.25585/1487765'},
 'id': 'b808403a208c4a39b291107ebef4873e',
 'name': '"Soil microbial response to elevated temperatures and increased '
         'carbon availability"',
 'principal_investigator': {'has raw value': 'Montana Smith',
                            'orcid': '0000-0002-8683-0050'},
 'publications': ['https://doi.org/10.1016/j.soilbio.2019.107561',
                  'Keiser, Ashley D., et al. "Peatland microbial community '
                  'response to altered climate tempered by nutrient '
                  'availability." Soil Biology and Biochemistry 137 (2019): '
                  '107561.'],
 'type': 'Study',
 'websites': ['https://microbiomedata.org/',
              'https://github.com/microbiomedata']}
```

**Comment by turbomam** [comment]
Disregarding issues

- #388 
- #389
- #390
- #391
- #392
- #393
- #394

The biosample set from the example NMDC Sample Metadata Template is in this state now. No encoding or validation has been performed yet.

```YAML
[
    {
        "id": "UUID:472894-473947-642384",
        "name": "P4_-0-10_4C",
        "env_package": "plant_associated",
        "investigation_type": "genome|metabolome",
        "type": "Biosample",
        "part_of": "b808403a208c4a39b291107ebef4873e",
        "growth_facil": "field",
        "geo_loc_name": "USA; Prosser, Washington; Washington State University-Irrigated Agriculture Research and Extension Center",
        "samp_mat_process": "snap freeze in liquid N",
        "store_cond": "fresh",
        "samp_store_temp": "4 degree Celsius",
        "env_broad_scale": "arid biome",
        "env_local_scale": "agricultural field",
        "env_medium": "agricultural soil",
        "lat_lon": "46.251709, -119.728663",
        "gold_path_field": "5424:Environmental:Terrestrial:Soil:Bulk soil:Agricultural land",
        "collection_date": "2020-05-21T12:00:00",
        "ncbi_taxonomy_name": "soil metagenome",
        "ID": "UUID:472894-473947-847398",
        "depth": {
            "has_raw_value": "0-1",
            "has_unit": "cm"
        },
        "elev": {
            "has_raw_value": 500,
            "has_unit": "m"
        },
        "samp_collect_device": "UUID:472894-473947-642384",
        "sieving": "1-.05mm"
    },
    {
        "id": "UUID:472894-473947-847396",
        "name": "L10_-20-30_13C-Gluc",
        "env_package": "soil",
        "source_mat_id": "UUID:472894-473947-847398",
        "investigation_type": "transcriptome|metabolome",
        "type": "Biosample",
        "part_of": "b808403a208c4a39b291107ebef4873e",
        "growth_facil": "field_incubation",
        "geo_loc_name": "USA; Prosser, Washington; Washington State University-Irrigated Agriculture Research and Extension Center",
        "samp_mat_process": "2micron sieve, wet to 25% gravimetric water capacity",
        "store_cond": "frozen",
        "samp_store_temp": "-80 degree Celsius",
        "env_broad_scale": "arid biome",
        "env_local_scale": "agricultural field",
        "env_medium": "agricultural soil",
        "lat_lon": "46.251709, -119.728663",
        "gold_path_field": "5424:Environmental:Terrestrial:Soil:Bulk soil:Agricultural land",
        "collection_date": "2020-05-21T13:30:00",
        "ncbi_taxonomy_name": "soil metagenome",
        "ID": "UUID:684267-410686-971057",
        "depth": {
            "has_raw_value": "0-1",
            "has_unit": "cm"
        },
        "elev": {
            "has_raw_value": 500,
            "has_unit": "m"
        },
        "isotope_exposure": "13C Glucose",
        "chem_administration": "1000\u00b5g of C (glucose)/g soil",
        "samp_collect_device": "UUID:472894-473947-847396",
        "sieving": "2mm"
    },
    {
        "id": "UUID:472894-473947-847398",
        "name": "6_J2_75-WHC",
        "env_package": "soil",
        "source_mat_id": "UUID:472894-473947-847398",
        "investigation_type": "organic matter",
        "type": "Biosample",
        "part_of": "b808403a208c4a39b291107ebef4873e",
        "growth_facil": "field",
        "geo_loc_name": "USA; Prosser, Washington; Washington State University-Irrigated Agriculture Research and Extension Center",
        "samp_mat_process": "aggregate separation at optimal moisture, dried at 100C",
        "store_cond": "other",
        "samp_store_temp": "room temperature",
        "env_broad_scale": "arid biome",
        "env_local_scale": "agricultural field",
        "env_medium": "agricultural soil",
        "lat_lon": "46.251709, -119.728663",
        "gold_path_field": "5424:Environmental:Terrestrial:Soil:Bulk soil:Agricultural land",
        "collection_date": "2020-05-21 00:00:00",
        "ncbi_taxonomy_name": "soil metagenome",
        "ID": "UUID:472894-473947-847396",
        "depth": {
            "has_raw_value": "0-1",
            "has_unit": "cm"
        },
        "elev": {
            "has_raw_value": 500,
            "has_unit": "m"
        },
        "chem_administration": "1000\u00b5g of C (glucose)/g soil",
        "watering_regm": "75% water holding capacity; moisture maintained every 3 days",
        "samp_collect_device": "UUID:472894-473947-847398",
        "sieving": "4mm"
    },
    {
        "id": "UUID:516394-970067-847398",
        "name": "T4-35",
        "env_package": "soil",
        "investigation_type": "lipidome|16S-Amplicon|ITS-Amplicon",
        "type": "Biosample",
        "part_of": "b808403a208c4a39b291107ebef4873e",
        "growth_facil": "field",
        "geo_loc_name": "USA; Prosser, Washington; Washington State University-Irrigated Agriculture Research and Extension Center",
        "samp_mat_process": "crushed via morter and pestle, temperature acclimation to 35C",
        "store_cond": "lyophilized",
        "samp_store_temp": "-80 degree Celsius",
        "env_broad_scale": "arid biome",
        "env_local_scale": "agricultural field",
        "env_medium": "agricultural soil",
        "lat_lon": "46.251500, -119.728483",
        "gold_path_field": "5424:Environmental:Terrestrial:Soil:Bulk soil:Agricultural land",
        "collection_date": "2021-01-05T15:05:00",
        "ncbi_taxonomy_name": "soil metagenome",
        "ID": "UUID:516394-970067-847398",
        "depth": {
            "has_raw_value": NaN,
            "has_unit": "cm"
        },
        "elev": {
            "has_raw_value": 1000,
            "has_unit": "m"
        },
        "air_temp_regm": "35C",
        "samp_collect_device": "UUID:516394-970067-847398",
        "sieving": "0.5-.25mm"
    },
    {
        "id": "UUID:684267-410686-971057",
        "name": "2020-05-21_S19",
        "env_package": "soil",
        "source_mat_id": "UUID:516394-970067-847398",
        "investigation_type": "proteome|genome",
        "type": "Biosample",
        "part_of": "b808403a208c4a39b291107ebef4873e",
        "growth_facil": "field",
        "geo_loc_name": "USA; Prosser, Washington; Washington State University-Irrigated Agriculture Research and Extension Center",
        "samp_mat_process": "ground via omni bead beater",
        "store_cond": "frozen",
        "samp_store_temp": "-20 degree Celsius",
        "env_broad_scale": "arid biome",
        "env_local_scale": "agricultural field",
        "env_medium": "agricultural soil",
        "lat_lon": "46.251500, -119.728483",
        "gold_path_field": "5424:Environmental:Terrestrial:Soil:Bulk soil:Agricultural land",
        "collection_date": "2021-03-11T09:25:00",
        "ncbi_taxonomy_name": "soil metagenome",
        "ID": "UUID:472894-473947-642384",
        "depth": {
            "has_raw_value": NaN,
            "has_unit": "cm"
        },
        "elev": {
            "has_raw_value": 1000,
            "has_unit": "m"
        },
        "samp_collect_device": "UUID:684267-410686-971057",
        "sieving": "2mm"
    }
]
```
