### ISSUE TITLE
NMDC Sample Metadata Template: currently undefined usage of samp_collect_device

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-metadata#390]
This is one component of issue #375

From `mixs.yaml`:

```YAML
  samp_collect_device:
    aliases:
      - sample collection device or method
    description: >-
       The method or device employed for collecting the sample
    multivalued: false
    is_a: attribute
    range: text value  ## syntax: {text}
    mappings:
      - mixs:samp_collect_device
    in_subset:
      - nucleic acid sequence source
 ```

I think the MenuTerms tab in the NMDC Sample Metadata Template is implying the following as descendants of the `samp_collect_device` slot:
- shovel
- slide_hammer_core
- deep_corer
- russian_corer
- sipper
- other-samp_collect_device

All of which would take a string range
